version: "3.8"

services:

  studio:
    image: supabase/studio:latest
    restart: unless-stopped
    environment:
      STUDIO_PG_META_URL: http://meta:8080
    ports:
      - "3000:3000"

  kong:
    image: kong:2.8
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml

  auth:
    image: supabase/gotrue:lastest
    restart: unless-stopped
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres

  rest:
    image: postgrest/postgrest:v10
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_DB_SCHEMA: public

  realtime:
    image: supabase/realtime:latest
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  storage:
    image: supabase/storage-api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres

  imgproxy:
    image: darthsim/imgproxy
    restart: unless-stopped

  meta:
    image: supabase/postgres-meta:latest
    restart: unless-stopped
    environment:
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}

  functions:
    image: ghcr.io/supabase/edge-runtime:v1.71.1
    restart: unless-stopped

  analytics:
    image: supabase/logflare
    restart: unless-stopped

  vector:
    image: timberio/vector:0.54.0-alpine
    restart: unless-stopped

  db:
    image: supabase/postgres:15.14.1.096
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  supavisor:
    image: supabase/supavisor:2.7.4
    restart: unless-stopped

volumes:
  db-data: